; Bai thuc hanh IoT so 2 - Pham Gia Huy - B23DCAT131
[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
build_src_filter = +<sketch.ino.cpp>
monitor_speed = 115200
lib_deps =
  beegee-tokyo/DHT sensor library for ESPx@1.19.0
  knolleary/PubSubClient@2.8
